DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS serv;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE serv(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    adresse TEXT UNIQUE NOT NULL,
    port INTEGER NOT NULL DEFAULT 502,
    size INTEGER NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);


